global MULTIPLE, COMMISSION, COMMISSION_MIN, COMMISSION_MAX, OPERATIONS_FOR_CASHBACK, CASHBACK, MAX_LUXURIES, TAX_LUXURIES
MULTIPLE = 50
COMMISSION = 0.015
COMMISSION_MIN = 30
COMMISSION_MAX = 600
OPERATIONS_FOR_CASHBACK = 3
CASHBACK = 0.03
MAX_LUXURIES = 5_000_000
TAX_LUXURIES = 0.1
